// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": neatThing Resource Client
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-neat-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-neat-thing-today
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// TodayNeatThingPath computes a request path to the today action of neatThing.
func TodayNeatThingPath() string {

	return fmt.Sprintf("/neat/thing/today")
}

// GET the neat thing for the day
func (c *Client) TodayNeatThing(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewTodayNeatThingRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewTodayNeatThingRequest create the request corresponding to the today action endpoint of the neatThing resource.
func (c *Client) NewTodayNeatThingRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
