// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": new Resource Client
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-new-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-new-thing-today
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// TodayNewPath computes a request path to the today action of new.
func TodayNewPath() string {

	return fmt.Sprintf("/new/thing/today")
}

// GET the new thing for the day
func (c *Client) TodayNew(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewTodayNewRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewTodayNewRequest create the request corresponding to the today action endpoint of the new resource.
func (c *Client) NewTodayNewRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
