consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  description: Discover something new each day by being given an item from a curated
    list.
  title: One new thing a day
  version: ""
paths:
  /new/thing/today:
    get:
      description: GET the new thing for the day
      operationId: newThing#today
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: today newThing
      tags:
      - newThing
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
