consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  NeatThing:
    description: NeatThing media type (default view)
    example:
      definition: Enim explicabo rerum ducimus qui.
      link: Minus quae eum ut iste.
      name: Enim id voluptatem velit.
    properties:
      definition:
        description: What the neat thing is
        example: Enim explicabo rerum ducimus qui.
        type: string
      link:
        description: Illustrative link for the neat thing
        example: Minus quae eum ut iste.
        type: string
      name:
        description: The neat thing
        example: Enim id voluptatem velit.
        type: string
    title: 'Mediatype identifier: application/vnd.douthitlab.neatthing; view=default'
    type: object
host: localhost:8080
info:
  description: Discover something neat each day by being given an item from a curated
    list.
  title: A neat thing each day
  version: ""
paths:
  /neat/thing/today:
    get:
      description: GET the neat thing for the day
      operationId: neatThing#today
      produces:
      - application/vnd.douthitlab.neatthing
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/NeatThing'
      schemes:
      - http
      summary: today neatThing
      tags:
      - neatThing
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
