swagger: "2.0"
info:
  title: One-new-thing-today
  description: Discover one new thing a day.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /neat/thing/today:
    get:
      tags:
      - neatThing
      summary: neatThingToday neatThing
      operationId: neatThing#neatThingToday
      responses:
        "204":
          description: No Content response.
          schema:
            $ref: '#/definitions/NeatThingNeatThingTodayResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      summary: Download ../../gen/http/openapi.json
      operationId: neatThing#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  NeatThingNeatThingTodayResponseBody:
    title: NeatThingNeatThingTodayResponseBody
    type: object
    properties:
      bibliography:
        type: array
        items:
          type: string
          example: Dolorem rerum.
        example:
        - Tempora et velit.
        - Quaerat et et.
        - Maiores quod pariatur.
      date:
        type: string
        description: When this was a neat thing
        example: "1973-02-12T22:42:29Z"
        format: date-time
      definition:
        type: string
        description: What the neat thing is
        example: Ratione voluptatem.
      link:
        type: string
        description: Illustrative link for the neat thing
        example: http://wuckerthettinger.com/carmel
        format: uri
      name:
        type: string
        description: The neat thing
        example: Quia sed odio voluptatem unde commodi doloribus.
    example:
      bibliography:
      - Dolore magni.
      - Distinctio quam quisquam dolore temporibus.
      date: "2010-03-05T05:22:24Z"
      definition: Aliquam sed illo accusantium tenetur dolorem voluptas.
      link: http://wisoky.biz/marguerite
      name: Libero nostrum sit ut optio debitis.
