// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": Application Controllers
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-new-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-new-thing-today
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// NewController is the controller interface for the New actions.
type NewController interface {
	goa.Muxer
	Today(*TodayNewContext) error
}

// MountNewController "mounts" a New resource controller on the given service.
func MountNewController(service *goa.Service, ctrl NewController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewTodayNewContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Today(rctx)
	}
	service.Mux.Handle("GET", "/new/thing/today", ctrl.MuxHandler("today", h, nil))
	service.LogInfo("mount", "ctrl", "New", "action", "Today", "route", "GET /new/thing/today")
}
