// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": Application Contexts
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-neat-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-neat-thing-today
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// TodayNeatThingContext provides the neatThing today action context.
type TodayNeatThingContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewTodayNeatThingContext parses the incoming request URL and body, performs validations and creates the
// context used by the neatThing controller today action.
func NewTodayNeatThingContext(ctx context.Context, r *http.Request, service *goa.Service) (*TodayNeatThingContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := TodayNeatThingContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *TodayNeatThingContext) OK(r *NeatThing) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKFull sends a HTTP response with status code 200.
func (ctx *TodayNeatThingContext) OKFull(r *NeatThingFull) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKName sends a HTTP response with status code 200.
func (ctx *TodayNeatThingContext) OKName(r *NeatThingName) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKNameDefinition sends a HTTP response with status code 200.
func (ctx *TodayNeatThingContext) OKNameDefinition(r *NeatThingNameDefinition) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKNameLink sends a HTTP response with status code 200.
func (ctx *TodayNeatThingContext) OKNameLink(r *NeatThingNameLink) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}
