// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": Application Contexts
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-new-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-new-thing-today
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// TodayNewContext provides the new today action context.
type TodayNewContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewTodayNewContext parses the incoming request URL and body, performs validations and creates the
// context used by the new controller today action.
func NewTodayNewContext(ctx context.Context, r *http.Request, service *goa.Service) (*TodayNewContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := TodayNewContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *TodayNewContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
