// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": Application User Types
//
// Command:
// $ goagen
// --design=ontt/design
// --out=$(GOPATH)/src/ontt
// --version=v1.3.1

package app
