// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Discovery": swagger TestHelpers
//
// Command:
// $ goagen
// --design=douthitlab.edu/one-new-thing-today/design
// --out=$(GOPATH)/src/douthitlab.edu/one-new-thing-today
// --version=v1.3.1

package test
